import gi
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk

# set sound (msb = 5, lsb = 1, sound = 2)
# 0xB0 - 0x00 - 0x05 (MSB sound bank selection)
# 0xB0 - 0x20 - 0x01 (LSB sound bank selection)
# 0xC0 - 0x02 (sound selection in the current sound bank)

categories = Gtk.ListStore(str)

categories.append([''])
categories.append(['Piano'])
categories.append(['Electric Piano'])
categories.append(['Mallet & Bell'])
categories.append(['Organ 1'])
categories.append(['Organ 2'])
categories.append(['Accordion'])
categories.append(['Guitar'])
categories.append(['Bass'])
categories.append(['Strings & Vocals'])
categories.append(['Brass'])
categories.append(['Trumpet & Trombone'])
categories.append(['Synth 1'])
categories.append(['Synth 2'])
categories.append(['Sax'])
categories.append(['Woodwind'])
categories.append(['Drum & Perc'])
categories.append(['SFX'])
categories.append(['Special'])

# msb, lsb, program change, category, name
sounds = Gtk.ListStore(int, int, int, str, str)

sounds.append([121,  0,   0, 'Piano',              'Acoustic Piano'])
sounds.append([121,  1,   0, 'Piano',              'Acoustic Piano Wide'])
sounds.append([121,  2,   0, 'Piano',              'Acoustic Piano Dark'])
sounds.append([121,  3,   0, 'Piano',              'Grand Piano'])
sounds.append([121,  4,   0, 'Piano',              'Classical Piano'])
sounds.append([121,  5,   0, 'Piano',              'L/R Piano'])
sounds.append([121,  6,   0, 'Piano',              'Piano & Vibes'])
sounds.append([121,  7,   0, 'Piano',              'Piano & Strings'])
sounds.append([121,  0,   1, 'Piano',              'Bright Piano'])
sounds.append([121,  1,   1, 'Piano',              'Bright Piano Wide'])
sounds.append([121,  2,   1, 'Piano',              'Piano Pad'])
sounds.append([121,  3,   1, 'Piano',              'Piano Pad 2'])
sounds.append([121,  4,   1, 'Piano',              'Piano Strings Pad'])
sounds.append([121,  0,   2, 'Piano',              'El Grand Piano'])
sounds.append([121,  1,   2, 'Piano',              'El Grand Piano Wide'])
sounds.append([121,  2,   2, 'Piano',              'M1 Piano'])
sounds.append([121,  3,   2, 'Piano',              '90\'s Piano'])
sounds.append([121,  4,   2, 'Piano',              '2000\'s Piano'])
sounds.append([121,  5,   2, 'Piano',              'Chorus Piano'])
sounds.append([121,  6,   2, 'Piano',              'Piano Layers'])
sounds.append([121,  0,   3, 'Piano',              'Honky Tonky Piano'])
sounds.append([121,  1,   3, 'Piano',              'Honky Tonky Piano Wide'])
sounds.append([121,  0,   4, 'Electric Piano',     'Electric Piano 1'])
sounds.append([121,  1,   4, 'Electric Piano',     'Detuned Electric Piano 1'])
sounds.append([121,  2,   4, 'Electric Piano',     'Electric Piano 1 Veloc. SW'])
sounds.append([121,  3,   4, 'Electric Piano',     '60\'s Electric Piano'])
sounds.append([121,  4,   4, 'Electric Piano',     'Vintage Electric Piano'])
sounds.append([121,  5,   4, 'Electric Piano',     'Pro-Dyno Electric Piano'])
sounds.append([121,  6,   4, 'Electric Piano',     'Pro Stage Electric Piano'])
sounds.append([121,  7,   4, 'Electric Piano',     'Studio Electric Piano'])
sounds.append([121,  8,   4, 'Electric Piano',     'R&B Electric Piano'])
sounds.append([121,  9,   4, 'Electric Piano',     'Thin Electric Piano'])
sounds.append([121, 10,   4, 'Electric Piano',     'DynoTine Electric Piano'])
sounds.append([121, 11,   4, 'Electric Piano',     'Club Electric Piano'])
sounds.append([121,  0,   5, 'Electric Piano',     'Electric Piano 2'])
sounds.append([121,  1,   5, 'Electric Piano',     'Detuned Electric Piano 2'])
sounds.append([121,  2,   5, 'Electric Piano',     'Electric Piano 2 Veloc. SW'])
sounds.append([121,  3,   5, 'Electric Piano',     'Electric Piano Legend'])
sounds.append([121,  4,   5, 'Electric Piano',     'Electric Piano Phase'])
sounds.append([121,  5,   5, 'Electric Piano',     'Synth Piano X'])
sounds.append([121,  6,   5, 'Electric Piano',     'Stereo Digital Electric Piano'])
sounds.append([121,  7,   5, 'Electric Piano',     'Classical Digital Electric Piano'])
sounds.append([121,  8,   5, 'Electric Piano',     'Hybrid Electric Piano'])
sounds.append([121,  9,   5, 'Electric Piano',     'Classical Tines'])
sounds.append([121, 10,   5, 'Electric Piano',     'Phantom Tines'])
sounds.append([121, 11,   5, 'Electric Piano',     'DW8000 Electric Piano'])
sounds.append([121, 12,   5, 'Electric Piano',     'Sweeping Electric Piano'])
sounds.append([121, 13,   5, 'Electric Piano',     'White Pad Electric Piano'])
sounds.append([121,  0,   6, 'Piano',              'Harpsichord'])
sounds.append([121,  1,   6, 'Piano',              'Harpsichord Octave'])
sounds.append([121,  2,   6, 'Piano',              'Harpsichord Wide'])
sounds.append([121,  3,   6, 'Piano',              'Harpsichord Korg Off'])
sounds.append([121,  4,   6, 'Piano',              'Harpsichord Korg'])
sounds.append([121,  0,   7, 'Piano',              'Clavichord'])
sounds.append([121,  1,   7, 'Piano',              'Pulse Clavichord'])
sounds.append([121,  2,   7, 'Piano',              'Clavichord Wah'])
sounds.append([121,  3,   7, 'Piano',              'Clavichord Snap'])
sounds.append([121,  4,   7, 'Piano',              'Sticky Clavichord'])
sounds.append([121,  0,   8, 'Mallet & Bell',      'Celesta'])
sounds.append([121,  0,   9, 'Mallet & Bell',      'Glockenspiel'])
sounds.append([121,  1,   9, 'Mallet & Bell',      'Sistro'])
sounds.append([121,  0,  10, 'Mallet & Bell',      'Music Box'])
sounds.append([121,  1,  10, 'Mallet & Bell',      'Orgel'])
sounds.append([121,  0,  11, 'Mallet & Bell',      'Vibraphone'])
sounds.append([121,  1,  11, 'Mallet & Bell',      'Vibraphone Wide'])
sounds.append([121,  2,  11, 'Mallet & Bell',      'Vibraphone 2'])
sounds.append([121,  0,  12, 'Mallet & Bell',      'Marimba'])
sounds.append([121,  1,  12, 'Mallet & Bell',      'Marimba Wide'])
sounds.append([121,  2,  12, 'Mallet & Bell',      'Rimba Key Off'])
sounds.append([121,  3,  12, 'Mallet & Bell',      'Monkey Skulls'])
sounds.append([121,  4,  12, 'Drum & Perc',        'Log Drum'])
sounds.append([121,  5,  12, 'Mallet & Bell',      'Mallet Clock'])
sounds.append([121,  6,  12, 'Mallet & Bell',      'Balaphon'])
sounds.append([121,  0,  13, 'Mallet & Bell',      'Xylophone'])
sounds.append([121,  0,  14, 'Mallet & Bell',      'Tubular Bell'])
sounds.append([121,  1,  14, 'Mallet & Bell',      'Church Bell'])
sounds.append([121,  2,  14, 'Mallet & Bell',      'Carillon'])
sounds.append([121,  3,  14, 'Mallet & Bell',      'Church Bell 2'])
sounds.append([121,  0,  15, 'Mallet & Bell',      'Dulcimer'])
sounds.append([121,  1,  15, 'Mallet & Bell',      'Santur'])
sounds.append([121,  0,  16, 'Organ 1',            'Drawbar Organ'])
sounds.append([121,  1,  16, 'Organ 1',            'Detuned Drawbar Organ'])
sounds.append([121,  2,  16, 'Organ 1',            'Italian 60\'s Organ'])
sounds.append([121,  3,  16, 'Organ 1',            'Drawbar Organ 2'])
sounds.append([121,  4,  16, 'Organ 1',            'Dark Jazz Organ'])
sounds.append([121,  5,  16, 'Organ 1',            'Iper Dark Organ'])
sounds.append([121,  6,  16, 'Organ 1',            'Full Drawbar Organ'])
sounds.append([121,  7,  16, 'Organ 1',            'DWGS Organ'])
sounds.append([121,  8,  16, 'Organ 1',            'Jass Organ'])
sounds.append([121,  9,  16, 'Organ 1',            'Gospel Organ'])
sounds.append([121, 10,  16, 'Organ 1',            'Good Old B'])
sounds.append([121, 11,  16, 'Organ 1',            'VOX Legend'])
sounds.append([121, 12,  16, 'Organ 1',            'Arabian Organ'])
sounds.append([121,  0,  17, 'Organ 1',            'Percussion Organ'])
sounds.append([121,  1,  17, 'Orgam 1',            'Detuned Percussion Organ'])
sounds.append([121,  2,  17, 'Organ 1',            'Percussion Organ 2'])
sounds.append([121,  3,  17, 'Organ 1',            'Old Wheels'])
sounds.append([121,  4,  17, 'Organ 1',            'Percussion BX3'])
sounds.append([121,  5,  17, 'Organ 1',            'M1 Organ'])
sounds.append([121,  6,  17, 'Organ 1',            'Tekno Organ Bass'])
sounds.append([121,  7,  17, 'Organ 1',            'BX3 Short Decay'])
sounds.append([121,  8,  17, 'Organ 1',            'Rotary Organ'])
sounds.append([121,  0,  18, 'Organ 1',            'Rock Organ'])
sounds.append([121,  1,  18, 'Organ 1',            'BX3 Veloc. SW'])
sounds.append([121,  2,  18, 'Organ 1',            'Killer B'])
sounds.append([121,  3,  18, 'Organ 1',            'Dirty B'])
sounds.append([121,  4,  18, 'Organ 1',            'Classic Click'])
sounds.append([121,  5,  18, 'Organ 1',            'Distortion Organ'])
sounds.append([121,  6,  18, 'Organ 1',            'Super BX Percussion'])
sounds.append([121,  7,  18, 'Organ 1',            'Dirty Jazz Organ'])
sounds.append([121,  8,  18, 'Organ 1',            'Percussion Short Decay'])
sounds.append([121,  9,  18, 'Organ 1',            'Percussion Wheels'])
sounds.append([121, 10,  18, 'Organ 1',            'Jimmy Organ'])
sounds.append([121,  0,  19, 'Organ 2',            'Church Organ 1'])
sounds.append([121,  1,  19, 'Organ 2',            'Church Octave Mix'])
sounds.append([121,  2,  19, 'Organ 2',            'Detuned Church Organ'])
sounds.append([121,  3,  19, 'Organ 2',            'Pipe Mixture'])
sounds.append([121,  4,  19, 'Organ 2',            'Church Pipes'])
sounds.append([121,  5,  19, 'Organ 2',            'Full Pipes'])
sounds.append([121,  6,  19, 'Organ 2',            'Pipe Tutti'])
sounds.append([121,  7,  19, 'Organ 2',            'Positive Organ'])
sounds.append([121,  0,  20, 'Organ 2',            'Reed Organ'])
sounds.append([121,  1,  20, 'Organ 2',            'Puff Organ'])
sounds.append([121,  2,  20, 'Organ 2',            'Small Pipe'])
sounds.append([121,  3,  20, 'Organ 2',            'Flauto Pipes'])
sounds.append([121,  0,  21, 'Accordion',          'Accordion'])
sounds.append([121,  1,  21, 'Accordion',          'Accordion 2'])
sounds.append([121,  2,  21, 'Accordion',          'Akordion'])
sounds.append([121,  3,  21, 'Accordion',          'Musette 1'])
sounds.append([121,  4,  21, 'Accordion',          'Musette 2'])
sounds.append([121,  5,  21, 'Accordion',          'Musette Clar'])
sounds.append([121,  6,  21, 'Accordion',          'Fisa 16+8'])
sounds.append([121,  7,  21, 'Accordion',          'Fisa 16+4'])
sounds.append([121,  8,  21, 'Accordion',          'Fisa Master'])
sounds.append([121,  9,  21, 'Accordion',          'Cassoto'])
sounds.append([121, 10,  21, 'Accordion',          'Arabian Accordion'])
sounds.append([121,  0,  22, 'Accordion',          'Harmonica'])
sounds.append([121,  1,  22, 'Accordion',          'Sweet Harmonica'])
sounds.append([121,  2,  22, 'Accordion',          'Harmonica 2'])
sounds.append([121,  0,  23, 'Accordion',          'Tango Accordion'])
sounds.append([121,  1,  23, 'Accordion',          'Fisa Tango!'])
sounds.append([121,  0,  24, 'Guitar',             'Nylon Guitar'])
sounds.append([121,  1,  24, 'Guitar',             'Ukelele'])
sounds.append([121,  2,  24, 'Guitar',             'Nylon Key Off'])
sounds.append([121,  3,  24, 'Guitar',             'Nylon Guitar 2'])
sounds.append([121,  4,  24, 'Guitar',             'Nylon Bossa'])
sounds.append([121,  5,  24, 'Guitar',             'Accoustic Guitar Key Off'])
sounds.append([121,  6,  24, 'Guitar',             'Spanish Guitar'])
sounds.append([121,  7,  24, 'Guitar',             'Guitar Strings'])
sounds.append([121,  0,  25, 'Guitar',             'Steel Guitar'])
sounds.append([121,  1,  25, 'Guitar',             '12 String Guitar'])
sounds.append([121,  2,  25, 'Guitar',             'Mandolin'])
sounds.append([121,  3,  25, 'Guitar',             'Steel & Body'])
sounds.append([121,  4,  25, 'Guitar',             'Steel Guitar 2'])
sounds.append([121,  5,  25, 'Guitar',             'Steel 12 Strings'])
sounds.append([121,  6,  25, 'Guitar',             'Hackbrett'])
sounds.append([121,  7,  25, 'Guitar',             'Finger Key Off'])
sounds.append([121,  8,  25, 'Guitar',             'Finger Tips'])
sounds.append([121,  9,  25, 'Guitar',             'Steel Folk Guitar'])
sounds.append([121, 10,  25, 'Guitar',             'Mandolin Key Off'])
sounds.append([121, 11,  25, 'Guitar',             'Mandolin Tremollo'])
sounds.append([121, 12,  25, 'Guitar',             'Ressonance Guitar'])
sounds.append([121,  0,  26, 'Guitar',             'Jazz Guitar'])
sounds.append([121,  1,  26, 'Guitar',             'Pedal Steel Guitar'])
sounds.append([121,  2,  26, 'Guitar',             'Club Jazz Guitar 1'])
sounds.append([121,  3,  26, 'Guitar',             'Club Jazz Guitar 2'])
sounds.append([121,  4,  26, 'Guitar',             'Pedal Steel Guitar 2'])
sounds.append([121,  0,  27, 'Guitar',             'Clean Guitar'])
sounds.append([121,  1,  27, 'Guitar',             'Detuned Clean Guitar'])
sounds.append([121,  2,  27, 'Guitar',             'Mid Tone Guitar'])
sounds.append([121,  3,  27, 'Guitar',             'Chorus Guitar'])
sounds.append([121,  4,  27, 'Guitar',             'Vintage Steel'])
sounds.append([121,  5,  27, 'Guitar',             'Processed Electric Guitar'])
sounds.append([121,  6,  27, 'Guitar',             'Single Coil'])
sounds.append([121,  7,  27, 'Guitar',             'New Strat Guitar'])
sounds.append([121,  8,  27, 'Guitar',             'Guitarish'])
sounds.append([121,  9,  27, 'Guitar',             'L&R Electric Guitar'])
sounds.append([121, 10,  27, 'Guitar',             'L&R Electric Guitar 2'])
sounds.append([121, 11,  27, 'Guitar',             'Country Nu'])
sounds.append([121, 12,  27, 'Guitar',             'Funky Wha SW'])
sounds.append([121,  0,  28, 'Guitar',             'Muted Guitar'])
sounds.append([121,  1,  28, 'Guitar',             'Funky Cut Guitar'])
sounds.append([121,  2,  28, 'Guitar',             'Mute Velo Guitar'])
sounds.append([121,  3,  28, 'Guitar',             'Jazz Man'])
sounds.append([121,  4,  28, 'Guitar',             'R&B Guitar'])
sounds.append([121,  5,  28, 'Guitar',             'Strat Chime'])
sounds.append([121,  6,  28, 'Guitar',             'Clean Muted Guitar'])
sounds.append([121,  7,  28, 'Guitar',             'Rhythm Electric Guitar'])
sounds.append([121,  8,  28, 'Guitar',             'Clean Funk'])
sounds.append([121,  9,  28, 'Guitar',             'Distortion Mute'])
sounds.append([121,  0,  29, 'Guitar',             'Overdrive Guitar'])
sounds.append([121,  1,  29, 'Guitar',             'Guitar Pinch'])
sounds.append([121,  0,  30, 'Guitar',             'Distortion Guitar'])
sounds.append([121,  1,  30, 'Guitar',             'Feedback Guitar'])
sounds.append([121,  2,  30, 'Guitar',             'Distortion Rhythm Guitar'])
sounds.append([121,  3,  30, 'Guitar',             'Joystick Guitar Y-'])
sounds.append([121,  4,  30, 'Guitar',             'Power Chords'])
sounds.append([121,  5,  30, 'Guitar',             'Mute Monster'])
sounds.append([121,  6,  30, 'Guitar',             'Wet Distorted Guitar'])
sounds.append([121,  7,  30, 'Guitar',             'Solo Distortion Guitar'])
sounds.append([121,  8,  30, 'Guitar',             'Stereo Distortion'])
sounds.append([121,  0,  31, 'Guitar',             'Guitar Harmonic'])
sounds.append([121,  1,  31, 'Guitar',             'Guitar Feedback'])
sounds.append([121,  2,  31, 'Guitar',             'Electric Guitar Harmonics'])
sounds.append([121,  0,  32, 'Bass',               'Acoustic Bass'])
sounds.append([121,  1,  32, 'Bass',               'Acoustic Bass Buzz'])
sounds.append([121,  2,  32, 'Bass',               'Bass & Ride'])
sounds.append([121,  0,  33, 'Bass',               'Finger Bass'])
sounds.append([121,  1,  33, 'Bass',               'Finger Slap Bass'])
sounds.append([121,  2,  33, 'Bass',               'Finger Electric Bass'])
sounds.append([121,  3,  33, 'Bass',               'Finger Electric Bass 2'])
sounds.append([121,  4,  33, 'Bass',               'Finger Electric Bass 3'])
sounds.append([121,  5,  33, 'Bass',               'Stick Bass'])
sounds.append([121,  0,  34, 'Bass',               'Picked Bass'])
sounds.append([121,  1,  34, 'Bass',               'Picked Electric Bass'])
sounds.append([121,  2,  34, 'Bass',               'Picked Electric Bass 2'])
sounds.append([121,  3,  34, 'Bass',               'Stein Bass'])
sounds.append([121,  4,  34, 'Bass',               'Guitar Bass'])
sounds.append([121,  5,  34, 'Bass',               'Bass Mute'])
sounds.append([121,  0,  35, 'Bass',               'Fretless Bass'])
sounds.append([121,  1,  35, 'Bass',               'Fretless Bass 2'])
sounds.append([121,  2,  35, 'Bass',               'Fretless SW'])
sounds.append([121,  3,  35, 'Bass',               'Sweet Fret'])
sounds.append([121,  4,  35, 'Bass',               'Dark R&B Bass'])
sounds.append([121,  0,  36, 'Bass',               'Slap Bass 1'])
sounds.append([121,  1,  36, 'Bass',               'Super SW Bass'])
sounds.append([121,  2,  36, 'Bass',               'Super SW Bass 2'])
sounds.append([121,  0,  37, 'Bass',               'Slap Bass 2'])
sounds.append([121,  1,  37, 'Bass',               'Thumb Bass'])
sounds.append([121,  2,  37, 'Bass',               'Dyna Bass'])
sounds.append([121,  0,  38, 'Bass',               'Synth Bass 1'])
sounds.append([121,  1,  38, 'Bass',               'Synth Bass Warm'])
sounds.append([121,  2,  38, 'Bass',               'Synth Bass Reso'])
sounds.append([121,  3,  38, 'Bass',               'Clavier Bass'])
sounds.append([121,  4,  38, 'Bass',               'Hammer'])
sounds.append([121,  5,  38, 'Bass',               '3030 Bass'])
sounds.append([121,  6,  38, 'Bass',               '3030 Square'])
sounds.append([121,  7,  38, 'Bass',               'Bass Square'])
sounds.append([121,  8,  38, 'Bass',               'Synth Bass Reso'])
sounds.append([121,  9,  38, 'Bass',               'Digi Bass 1'])
sounds.append([121, 10,  38, 'Bass',               'Digi Bass 2'])
sounds.append([121, 11,  38, 'Bass',               'Digi Bass 3'])
sounds.append([121, 12,  38, 'Bass',               'Blind As A Bat'])
sounds.append([121, 13,  38, 'Bass',               'Jungle Bass'])
sounds.append([121, 14,  38, 'Synth 2',            'Auto Pilot'])
sounds.append([121, 15,  38, 'Bass',               'Hybrid Bass'])
sounds.append([121, 16,  38, 'Bass',               'Dr. Octave'])
sounds.append([121,  0,  39, 'Bass',               'Synth Bass 2'])
sounds.append([121,  1,  39, 'Bass',               'Attack Bass'])
sounds.append([121,  2,  39, 'Bass',               'Rubber Bass'])
sounds.append([121,  3,  39, 'Bass',               'Attack Pulse'])
sounds.append([121,  4,  39, 'Bass',               'Euro Bass'])
sounds.append([121,  5,  39, 'Bass',               'Jungle Rez'])
sounds.append([121,  6,  39, 'Bass',               'Nasty Bass'])
sounds.append([121,  7,  39, 'Bass',               'Phat Bass'])
sounds.append([121,  8,  39, 'Bass',               'Poinker Bass'])
sounds.append([121,  0,  40, 'Strings & Vocals',   'Violin'])
sounds.append([121,  1,  40, 'Strings & Vocals',   'Slow Attack Violin'])
sounds.append([121,  2,  40, 'Strings & Vocals',   'Solo Violin'])
sounds.append([121,  3,  40, 'Strings & Vocals',   'Slow Violin'])
sounds.append([121,  0,  41, 'Strings & Vocals',   'Viola'])
sounds.append([121,  0,  42, 'Strings & Vocals',   'Cello'])
sounds.append([121,  0,  43, 'Strings & Vocals',   'Contrabass'])
sounds.append([121,  0,  44, 'Strings & Vocals',   'Tremolo Strings'])
sounds.append([121,  0,  45, 'Strings & Vocals',   'Pizzicato Strings'])
sounds.append([121,  1,  45, 'Strings & Vocals',   'Pizzicato Ensemble'])
sounds.append([121,  2,  45, 'Strings & Vocals',   'Pizzicato Section'])
sounds.append([121,  3,  45, 'Strings & Vocals',   'Double Strings'])
sounds.append([121,  0,  46, 'Strings & Vocals',   'Orchestral Harp'])
sounds.append([121,  1,  46, 'Strings & Vocals',   'Yang Chin'])
sounds.append([121,  0,  47, 'Drum & Perc',        'Timpani'])
sounds.append([121,  0,  48, 'Strings & Vocals',   'Strings Ensemble 1'])
sounds.append([121,  1,  48, 'Strings & Vocals',   'String & Brass'])
sounds.append([121,  2,  48, 'Strings & Vocals',   '60\'s Strings'])
sounds.append([121,  3,  48, 'Strings & Vocals',   'Stereo Strings'])
sounds.append([121,  4,  48, 'Strings & Vocals',   'Legatto Strings'])
sounds.append([121,  5,  48, 'Strings & Vocals',   'i3 Strings'])
sounds.append([121,  6,  48, 'Strings & Vocals',   'N Strings'])
sounds.append([121,  7,  48, 'Strings & Vocals',   'Arco Strings'])
sounds.append([121,  8,  48, 'Strings & Vocals',   'Octave Strings'])
sounds.append([121,  9,  48, 'Strings & Vocals',   'String Quartet'])
sounds.append([121, 10,  48, 'Strings & Vocals',   'Symphonic Bows'])
sounds.append([121, 11,  48, 'Strings & Vocals',   'Ensemble & Solo'])
sounds.append([121, 12,  48, 'Strings & Vocals',   'Camera Strings'])
sounds.append([121, 13,  48, 'Strings & Vocals',   'Arab Strings'])
sounds.append([121,  0,  49, 'Strings & Vocals',   'Strings Ensemble 2'])
sounds.append([121,  1,  49, 'Strings & Vocals',   'Sweeper Strings'])
sounds.append([121,  0,  50, 'Strings & Vocals',   'Synth Strings 1'])
sounds.append([121,  1,  50, 'Strings & Vocals',   'Synth Strings 3'])
sounds.append([121,  2,  50, 'Strings & Vocals',   'Analog Strings'])
sounds.append([121,  3,  50, 'Strings & Vocals',   'Analog Velvet Strings'])
sounds.append([121,  4,  50, 'Strings & Vocals',   'Odissey'])
sounds.append([121,  0,  51, 'Strings & Vocals',   'Synth Strings 2'])
sounds.append([121,  0,  52, 'Strings & Vocals',   'Choir Aahs'])
sounds.append([121,  1,  52, 'Strings & Vocals',   'Choir Aahs 2'])
sounds.append([121,  2,  52, 'Strings & Vocals',   'Oooh Voices'])
sounds.append([121,  3,  52, 'Strings & Vocals',   'Oooh Slow Voices'])
sounds.append([121,  4,  52, 'Strings & Vocals',   'Take Voices'])
sounds.append([121,  5,  52, 'Strings & Vocals',   'Take Voices 2'])
sounds.append([121,  6,  52, 'Strings & Vocals',   'Oooh Choir'])
sounds.append([121,  7,  52, 'Strings & Vocals',   'Aaah Choir'])
sounds.append([121,  8,  52, 'Strings & Vocals',   'Mmmh Choir'])
sounds.append([121,  9,  52, 'Strings & Vocals',   'Oooh - Aaah Voices'])
sounds.append([121, 10,  52, 'Strings & Vocals',   'Slow Choir'])
sounds.append([121, 11,  52, 'Strings & Vocals',   'Grand Choir'])
sounds.append([121, 12,  52, 'Strings & Vocals',   'Choir Light'])
sounds.append([121, 13,  52, 'Strings & Vocals',   'String Choir'])
sounds.append([121,  0,  53, 'Strings & Vocals',   'Voice Ooohs'])
sounds.append([121,  1,  53, 'Strings & Vocals',   'Humming'])
sounds.append([121,  2,  53, 'Strings & Vocals',   'Doolally'])
sounds.append([121,  3,  53, 'Strings & Vocals',   'Airways'])
sounds.append([121,  0,  54, 'Strings & Vocals',   'Synth Voice'])
sounds.append([121,  1,  54, 'Strings & Vocals',   'Analog Voice'])
sounds.append([121,  2,  54, 'Strings & Vocals',   'Vocalesque'])
sounds.append([121,  3,  54, 'Strings & Vocals',   'Vocalscape'])
sounds.append([121,  4,  54, 'Strings & Vocals',   'Classic Vox'])
sounds.append([121,  5,  54, 'Strings & Vocals',   'Dream Voice'])
sounds.append([121,  0,  55, 'Brass',              'Orchestral Hit'])
sounds.append([121,  1,  55, 'Brass',              'Brass Hit Plus'])
sounds.append([121,  2,  55, 'Brass',              '6th Hit'])
sounds.append([121,  3,  55, 'Brass',              'Euro Hit'])
sounds.append([121,  4,  55, 'Brass',              'Brass Impact'])
sounds.append([121,  5,  55, 'SFX',                'Hit In India'])
sounds.append([121,  6,  55, 'Synth 2',            'Wild Arp'])
sounds.append([121,  7,  55, 'Synth 2',            'Flip Blip'])
sounds.append([121,  0,  56, 'Trumpet & Trombone', 'Trumpet'])
sounds.append([121,  1,  56, 'Trumpet & Trombone', 'Dark Trumpet'])
sounds.append([121,  2,  56, 'Trumpet & Trombone', 'Trumpet 2'])
sounds.append([121,  3,  56, 'Trumpet & Trombone', 'Mono Trumpet'])
sounds.append([121,  4,  56, 'Trumpet & Trombone', 'Trumpet Expression'])
sounds.append([121,  5,  56, 'Trumpet & Trombone', 'Trumpet Pitch'])
sounds.append([121,  6,  56, 'Trumpet & Trombone', 'Dual Trumpet'])
sounds.append([121,  7,  56, 'Trumpet & Trombone', 'Flugel Horn'])
sounds.append([121,  8,  56, 'Trumpet & Trombone', 'Warm Flugel'])
sounds.append([121,  9,  56, 'Trumpet & Trombone', 'Be Bop Cornet'])
sounds.append([121,  0,  57, 'Trumpet & Trombone', 'Trombone'])
sounds.append([121,  1,  57, 'Trumpet & Trombone', 'Trombone 2'])
sounds.append([121,  2,  57, 'Trumpet & Trombone', 'Bright Trombone'])
sounds.append([121,  3,  57, 'Trumpet & Trombone', 'Hard Trombone'])
sounds.append([121,  4,  57, 'Trumpet & Trombone', 'Soft Trombone'])
sounds.append([121,  5,  57, 'Trumpet & Trombone', 'Pitch Trombone'])
sounds.append([121,  0,  58, 'Trumpet & Trombone', 'Tuba'])
sounds.append([121,  1,  58, 'Trumpet & Trombone', 'Ob. Tuba'])
sounds.append([121,  2,  58, 'Trumpet & Trombone', 'Tuba Gold'])
sounds.append([121,  3,  58, 'Trumpet & Trombone', 'Dynabone'])
sounds.append([121,  0,  59, 'Trumpet & Trombone', 'Muted Trumpet'])
sounds.append([121,  1,  59, 'Trumpet & Trombone', 'Muted Trumpet 2'])
sounds.append([121,  2,  59, 'Trumpet & Trombone', 'Wha Trumpet'])
sounds.append([121,  3,  59, 'Trumpet & Trombone', 'Muted Ensemble'])
sounds.append([121,  4,  59, 'Trumpet & Trombone', 'Muted Ensemble 2'])
sounds.append([121,  0,  60, 'Brass',              'French Horn'])
sounds.append([121,  1,  60, 'Brass',              'French Horn 2'])
sounds.append([121,  2,  60, 'Brass',              'French Section'])
sounds.append([121,  3,  60, 'Brass',              'Classic Horn'])
sounds.append([121,  4,  60, 'Brass',              'Horns & Ensemble'])
sounds.append([121,  0,  61, 'Brass',              'Brass Section 1'])
sounds.append([121,  1,  61, 'Brass',              'Brass Section 2'])
sounds.append([121,  2,  61, 'Brass',              'Tight Brass'])
sounds.append([121,  3,  61, 'Brass',              'Glen & Friend'])
sounds.append([121,  4,  61, 'Brass',              'Big Band Brass'])
sounds.append([121,  5,  61, 'Brass',              'Sax & Brass'])
sounds.append([121,  6,  61, 'Brass',              'Glen & Boys'])
sounds.append([121,  7,  61, 'Brass',              'Trumpet & Brass'])
sounds.append([121,  8,  61, 'Brass',              'Attack Brass'])
sounds.append([121,  9,  61, 'Brass',              'Trumpet Ensemble'])
sounds.append([121, 10,  61, 'Brass',              'Trombone Ensemble'])
sounds.append([121, 11,  61, 'Brass',              'Trombones'])
sounds.append([121, 12,  61, 'Brass',              'Tight Brass 2'])
sounds.append([121, 13,  61, 'Brass',              'Fat Brass'])
sounds.append([121, 14,  61, 'Brass',              'Dyna Brass'])
sounds.append([121, 15,  61, 'Brass',              'Brass Expression'])
sounds.append([121, 16,  61, 'Brass',              'Brass Band'])
sounds.append([121, 17,  61, 'Brass',              'Film Brass'])
sounds.append([121, 18,  61, 'Brass',              'Brass Slow'])
sounds.append([121, 19,  61, 'Brass',              'Fanfare'])
sounds.append([121, 20,  61, 'Brass',              'Movie Brass'])
sounds.append([121, 21,  61, 'Brass',              'Power Brass'])
sounds.append([121, 22,  61, 'Brass',              'Dyna Brass 2'])
sounds.append([121, 23,  61, 'Brass',              'Sfz Brass'])
sounds.append([121, 24,  61, 'Brass',              'Double Brass'])
sounds.append([121, 25,  61, 'Brass',              'Brass Hit'])
sounds.append([121, 26,  61, 'Brass',              'Brass Fall'])
sounds.append([121,  0,  62, 'Brass',              'Synth Brass 1'])
sounds.append([121,  1,  62, 'Brass',              'Synth Brass 3'])
sounds.append([121,  2,  62, 'Brass',              'Analog Brass 1'])
sounds.append([121,  3,  62, 'Brass',              'Jump Brass'])
sounds.append([121,  4,  62, 'Brass',              'Electrik Brass'])
sounds.append([121,  5,  62, 'Brass',              'Synth Brass 5'])
sounds.append([121,  0,  63, 'Brass',              'Synth Brass 2'])
sounds.append([121,  1,  63, 'Brass',              'Synth Brass 4'])
sounds.append([121,  2,  63, 'Brass',              'Analog Brass 2'])
sounds.append([121,  3,  63, 'Brass',              'Brass Pad'])
sounds.append([121,  4,  63, 'Synth 1',            'Big Panner'])
sounds.append([121,  0,  64, 'Sax',                'Soprano Sax'])
sounds.append([121,  1,  64, 'Sax',                'Sweet Soprano'])
sounds.append([121,  0,  65, 'Sax',                'Alto Sax'])
sounds.append([121,  1,  65, 'Sax',                'Alto Breath'])
sounds.append([121,  2,  65, 'Sax',                'Sax Ensemble'])
sounds.append([121,  3,  65, 'Sax',                'Breathy Alto'])
sounds.append([121,  4,  65, 'Sax',                'Alto Sax Growl'])
sounds.append([121,  0,  66, 'Sax',                'Tenor Sax'])
sounds.append([121,  1,  66, 'Sax',                'Tenor Noise'])
sounds.append([121,  2,  66, 'Sax',                'Soft Tenor'])
sounds.append([121,  3,  66, 'Sax',                'Tenor Breath'])
sounds.append([121,  4,  66, 'Sax',                'Tenor Growl'])
sounds.append([121,  5,  66, 'Sax',                'Folk Sax'])
sounds.append([121,  0,  67, 'Sax',                'Baritone Sax'])
sounds.append([121,  1,  67, 'Sax',                'Baritone Growl'])
sounds.append([121,  2,  67, 'Sax',                'Breathy Baritone'])
sounds.append([121,  0,  68, 'Woodwind',           'Oboe'])
sounds.append([121,  1,  68, 'Woodwind',           'Double Reed'])
sounds.append([121,  0,  69, 'Woodwind',           'English Horn'])
sounds.append([121,  1,  69, 'Woodwind',           'English Horn 2'])
sounds.append([121,  0,  70, 'Woodwind',           'Bassoon'])
sounds.append([121,  0,  71, 'Woodwind',           'Clarinet'])
sounds.append([121,  1,  71, 'Woodwind',           'Jazz Clarinet'])
sounds.append([121,  2,  71, 'Woodwind',           'Clarinet G'])
sounds.append([121,  3,  71, 'Woodwind',           'Section Winds'])
sounds.append([121,  4,  71, 'Woodwind',           'Section Winds 2'])
sounds.append([121,  5,  71, 'Woodwind',           'Clarinet Ensemble'])
sounds.append([121,  6,  71, 'Woodwind',           'Woodwinds'])
sounds.append([121,  7,  71, 'Woodwind',           'Folk Clarinet'])
sounds.append([121,  0,  72, 'Woodwind',           'Piccolo'])
sounds.append([121,  1,  72, 'Woodwind',           'Small Orchestra'])
sounds.append([121,  2,  72, 'Woodwind',           'Nay'])
sounds.append([121,  0,  73, 'Woodwind',           'Flute'])
sounds.append([121,  1,  73, 'Woodwind',           'Jazz Flute'])
sounds.append([121,  2,  73, 'Woodwind',           'Flute Switch'])
sounds.append([121,  3,  73, 'Woodwind',           'Flute Dyn 5th'])
sounds.append([121,  4,  73, 'Woodwind',           'Flute Frull'])
sounds.append([121,  5,  73, 'Woodwind',           'Orchetral Flute'])
sounds.append([121,  6,  73, 'Woodwind',           'Flute Muted'])
sounds.append([121,  7,  73, 'Woodwind',           'Wooden Flute'])
sounds.append([121,  8,  73, 'Woodwind',           'Bambu Flute'])
sounds.append([121,  9,  73, 'Woodwind',           'Flute 2'])
sounds.append([121,  0,  74, 'Woodwind',           'Recorder'])
sounds.append([121,  1,  74, 'Woodwind',           'Recorder 2'])
sounds.append([121,  0,  75, 'Woodwind',           'Pan Flute'])
sounds.append([121,  1,  75, 'Woodwind',           'Kawala'])
sounds.append([121,  0,  76, 'Woodwind',           'Blown Bottle'])
sounds.append([121,  0,  77, 'Woodwind',           'Shakuhachi'])
sounds.append([121,  1,  77, 'Woodwind',           'Old Shaku'])
sounds.append([121,  2,  77, 'Woodwind',           'Shaku 2'])
sounds.append([121,  0,  78, 'Woodwind',           'Whistle'])
sounds.append([121,  1,  78, 'Woodwind',           'Whistle 2'])
sounds.append([121,  0,  79, 'Woodwind',           'Ocarina'])
sounds.append([121,  0,  80, 'Synth 2',            'Lead Square'])
sounds.append([121,  1,  80, 'Synth 2',            'Lead Square 2'])
sounds.append([121,  2,  80, 'Synth 2',            'Lead Sine'])
sounds.append([121,  3,  80, 'Synth 2',            'Old Portamento'])
sounds.append([121,  4,  80, 'Synth 2',            'Dance Lead'])
sounds.append([121,  5,  80, 'Synth 2',            'Wave Lead'])
sounds.append([121,  6,  80, 'Synth 2',            'Sine Wave'])
sounds.append([121,  7,  80, 'Synth 2',            'Analog Lead'])
sounds.append([121,  8,  80, 'Synth 2',            'Old & Analog'])
sounds.append([121,  9,  80, 'Synth 2',            'Gliding Square'])
sounds.append([121, 10,  80, 'Synth 2',            'Sine Switch'])
sounds.append([121, 11,  80, 'Synth 2',            'Square Rez'])
sounds.append([121,  0,  81, 'Synth 2',            'Lead Saw'])
sounds.append([121,  1,  81, 'Synth 2',            'Lead Saw 2'])
sounds.append([121,  2,  81, 'Synth 2',            'Lead Saw Pulse'])
sounds.append([121,  3,  81, 'Synth 2',            'Lead Double Saw'])
sounds.append([121,  4,  81, 'Synth 2',            'Sequence Analog'])
sounds.append([121,  5,  81, 'Synth 2',            'Power Saw'])
sounds.append([121,  6,  81, 'Synth 2',            'Octo Lead'])
sounds.append([121,  7,  81, 'Synth 2',            'Sequence Lead'])
sounds.append([121,  8,  81, 'Synth 2',            'Phat Saw Lead'])
sounds.append([121,  9,  81, 'Synth 2',            'Glide Lead'])
sounds.append([121, 10,  81, 'Synth 2',            'Fire Wave'])
sounds.append([121, 11,  81, 'Synth 2',            'Rezbo'])
sounds.append([121, 12,  81, 'Synth 2',            'Synth Pianoid'])
sounds.append([121,  0,  82, 'Synth 2',            'Calliope'])
sounds.append([121,  0,  83, 'Synth 2',            'Chiff'])
sounds.append([121,  0,  84, 'Synth 2',            'Charang'])
sounds.append([121,  1,  84, 'Synth 2',            'Wire Lead'])
sounds.append([121,  2,  84, 'Synth 2',            'Synchro City'])
sounds.append([121,  3,  84, 'Synth 2',            'Sync Kron'])
sounds.append([121,  4,  84, 'Synth 2',            'Metallic Rez'])
sounds.append([121,  5,  84, 'Synth 2',            'Brian Sync'])
sounds.append([121,  6,  84, 'Synth 2',            'Arp Twins'])
sounds.append([121,  0,  85, 'Strings & Vocals',   'Voice Lead'])
sounds.append([121,  1,  85, 'Strings & Vocals',   'Ether Voices'])
sounds.append([121,  2,  85, 'Strings & Vocals',   'Cyber Choir'])
sounds.append([121,  0,  86, 'Synth 2',            'Fifths Lead'])
sounds.append([121,  1,  86, 'Synth 2',            'Crimson 5ths'])
sounds.append([121,  0,  87, 'Synth 2',            'Bass & Lead'])
sounds.append([121,  1,  87, 'Synth 2',            'Soft Wrl'])
sounds.append([121,  2,  87, 'Synth 2',            'Electro Lead'])
sounds.append([121,  3,  87, 'Synth 2',            'Rich Lead'])
sounds.append([121,  4,  87, 'Synth 2',            'Thin Analog Lead'])
sounds.append([121,  5,  87, 'Synth 2',            'Espress Lead'])
sounds.append([121,  6,  87, 'Synth 2',            'Hip Hop Lead'])
sounds.append([121,  7,  87, 'Synth 2',            'Square Bass'])
sounds.append([121,  8,  87, 'Synth 2',            'Big & Raw'])
sounds.append([121,  9,  87, 'Synth 2',            'Cat Lead'])
sounds.append([121,  0,  88, 'Synth 1',            'New Age Pad'])
sounds.append([121,  1,  88, 'Synth 1',            'Virtual Travel'])
sounds.append([121,  2,  88, 'Synth 1',            'Arp Angeles'])
sounds.append([121,  0,  89, 'Synth 1',            'Warm Pad'])
sounds.append([121,  1,  89, 'Synth 1',            'Sine Pad'])
sounds.append([121,  2,  89, 'Synth 1',            'Master Pad'])
sounds.append([121,  3,  89, 'Synth 1',            'Power Synth'])
sounds.append([121,  4,  89, 'Synth 1',            'The Pad'])
sounds.append([121,  5,  89, 'Synth 1',            'Money Pad'])
sounds.append([121,  6,  89, 'Synth 1',            'Dark Pad'])
sounds.append([121,  7,  89, 'Synth 1',            'Freedom Pad'])
sounds.append([121,  8,  89, 'Synth 1',            'Analog Pad'])
sounds.append([121,  0,  90, 'Synth 1',            'Polysynth'])
sounds.append([121,  1,  90, 'Synth 1',            'Reso Sweep'])
sounds.append([121,  2,  90, 'Synth 1',            'Sky Watcher'])
sounds.append([121,  3,  90, 'Synth 1',            'Synth Sweeper'])
sounds.append([121,  4,  90, 'Synth 1',            'Super Sweeper'])
sounds.append([121,  5,  90, 'Synth 1',            'Wave Sweep'])
sounds.append([121,  6,  90, 'Synth 1',            'Cross Sweep'])
sounds.append([121,  7,  90, 'Synth 1',            'Digital PolySix'])
sounds.append([121,  8,  90, 'Synth 1',            'Noisy Stab'])
sounds.append([121,  9,  90, 'Synth 1',            'Mega Synth'])
sounds.append([121, 10,  90, 'Synth 1',            'Techno Phonic'])
sounds.append([121, 11,  90, 'Synth 1',            'Farluce'])
sounds.append([121,  0,  91, 'Synth 1',            'Choir Pad'])
sounds.append([121,  1,  91, 'Synth 1',            'Itopia Pad'])
sounds.append([121,  2,  91, 'Strings & Vocals',   'Fresh Air'])
sounds.append([121,  3,  91, 'Synth 1',            'Heaven'])
sounds.append([121,  4,  91, 'Synth 1',            'Pop Synth Pad'])
sounds.append([121,  5,  91, 'Synth 1',            'Future Pad'])
sounds.append([121,  6,  91, 'Synth 1',            'Tsunami Wave'])
sounds.append([121,  7,  91, 'Synth 1',            'Fresh Breath'])
sounds.append([121,  8,  91, 'Synth 1',            'Ravelian Pad'])
sounds.append([121,  9,  91, 'Synth 1',            'Full Vox Pad'])
sounds.append([121, 10,  91, 'Synth 1',            'Dance ReMix'])
sounds.append([121,  0,  92, 'Synth 1',            'Bowed Glass'])
sounds.append([121,  0,  93, 'Synth 1',            'Metallic Pad'])
sounds.append([121,  1,  93, 'Synth 1',            'Cosmic'])
sounds.append([121,  0,  94, 'Synth 1',            'Halo Pad'])
sounds.append([121,  0,  95, 'Synth 1',            'Sweep Pad'])
sounds.append([121,  1,  95, 'Synth 1',            'Astral Dream'])
sounds.append([121,  2,  95, 'Synth 1',            'Meditate'])
sounds.append([121,  3,  95, 'Synth 1',            'Dark Element'])
sounds.append([121,  4,  95, 'Synth 1',            'Mellow Pad'])
sounds.append([121,  5,  95, 'Synth 1',            'Cinema Pad'])
sounds.append([121,  0,  96, 'Synth 1',            'Ice Rain'])
sounds.append([121,  1,  96, 'Synth 1',            'Motion Ocean'])
sounds.append([121,  2,  96, 'Synth 1',            'Caribbean'])
sounds.append([121,  0,  97, 'Synth 1',            'Soundtrack'])
sounds.append([121,  1,  97, 'Synth 1',            'Air Clouds'])
sounds.append([121,  2,  97, 'Synth 1',            'Reso Down'])
sounds.append([121,  3,  97, 'Synth 1',            'Tinklin Pad'])
sounds.append([121,  4,  97, 'Synth 1',            'Pods In Pad'])
sounds.append([121,  5,  97, 'Synth 1',            'Noble Pad'])
sounds.append([121,  6,  97, 'Synth 1',            'Rave'])
sounds.append([121,  7,  97, 'Synth 1',            'Elastick Pad'])
sounds.append([121,  0,  98, 'Synth 2',            'Crystal'])
sounds.append([121,  1,  98, 'SFX',                'Synth Mallet'])
sounds.append([121,  2,  98, 'Mallet & Bell',      'Vs Bell Boy'])
sounds.append([121,  3,  98, 'Mallet & Bell',      'Krystal Bell'])
sounds.append([121,  4,  98, 'Mallet & Bel',       'Digi Bel'])
sounds.append([121,  5,  98, 'Synth 1',            'Moving Bell'])
sounds.append([121,  6,  98, 'Mallet & Bell',      'Bell Pad'])
sounds.append([121,  7,  98, 'Synth 1',            'Bell Choir'])
sounds.append([121,  0,  99, 'Synth 2',            'Atmosphere'])
sounds.append([121,  0, 100, 'Synth 2',            'Brightness'])
sounds.append([121,  1, 100, 'Synth 1',            'Lonely Spin'])
sounds.append([121,  2, 100, 'Synth 1',            'Synth Ghostly'])
sounds.append([121,  0, 101, 'SFX',                'Goblins'])
sounds.append([121,  1, 101, 'Synth 2',            'Motion Raver'])
sounds.append([121,  2, 101, 'Syhtn 1',            'Digi IcePad'])
sounds.append([121,  0, 102, 'SFX',                'Echo Drops'])
sounds.append([121,  1, 102, 'SFX',                'Echo Bell'])
sounds.append([121,  2, 102, 'SFX',                'Echo Pan'])
sounds.append([121,  3, 102, 'Synth 2',            'Band Passed'])
sounds.append([121,  4, 102, 'Synth 2',            'Pan Reso'])
sounds.append([121,  5, 102, 'Synth 1',            'Moon Cycles'])
sounds.append([121,  0, 103, 'SFX',                'Star Theme'])
sounds.append([121,  0, 104, 'Guitar',             'Sitar'])
sounds.append([121,  1, 104, 'Guitar',             'Sitar 2'])
sounds.append([121,  2, 104, 'Guitar',             'Sitar Tambourine'])
sounds.append([121,  3, 104, 'Guitar',             'Indian Stars'])
sounds.append([121,  4, 104, 'Guitar',             'Indian Frets'])
sounds.append([121,  5, 104, 'Guitar',             'Bouzouki'])
sounds.append([121,  6, 104, 'Guitar',             'Tambra'])
sounds.append([121,  0, 105, 'Guitar',             'Banjo'])
sounds.append([121,  1, 105, 'Guitar',             'Banjo Key Off'])
sounds.append([121,  2, 105, 'Guitar',             'Oud'])
sounds.append([121,  3, 105, 'SFX',                'Jaw Harp'])
sounds.append([121,  0, 106, 'Guitar',             'Shamisen'])
sounds.append([121,  0, 107, 'Guitar',             'Koto'])
sounds.append([121,  1, 107, 'Guitar',             'Taisho Koto'])
sounds.append([121,  2, 107, 'Guitar',             'Kanun'])
sounds.append([121,  3, 107, 'Guitar',             'Kanun Tremolo'])
sounds.append([121,  4, 107, 'Guitar',             'Kanun Mix'])
sounds.append([121,  0, 108, 'Mallet & Bell',      'Kalimba'])
sounds.append([121,  1, 108, 'Mallet & Bell',      'Velo Kalimba'])
sounds.append([121,  0, 109, 'Woodwind',           'Bag Pipe'])
sounds.append([121,  1, 109, 'Woodwind',           'War Pipes'])
sounds.append([121,  0, 110, 'Strings & Vocals',   'Fiddle'])
sounds.append([121,  0, 111, 'Woodwind',           'Shanai'])
sounds.append([121,  1, 111, 'Woodwind',           'Zurna'])
sounds.append([121,  2, 111, 'Woodwind',           'Hichirki'])
sounds.append([121,  0, 112, 'Mallet & Bell',      'Tinkle Bell'])
sounds.append([121,  1, 112, 'Mallet & Bell',      'Gamelan'])
sounds.append([121,  2, 112, 'Mallet & Bell',      'Bali Gamelan'])
sounds.append([121,  3, 112, 'Mallet & Bell',      'Garbage Mallet'])
sounds.append([121,  0, 113, 'Drum & Perc',        'Agogo'])
sounds.append([121,  0, 114, 'Mallet & Bell',      'Steel Drums'])
sounds.append([121,  1, 114, 'Mallet & Bell',      'Warm Steel'])
sounds.append([121,  0, 115, 'Drum & Perc',        'Woodblock'])
sounds.append([121,  1, 115, 'Drum & Perc',        'Castanets'])
sounds.append([121,  0, 116, 'Drum & Perc',        'Taiko Drum'])
sounds.append([121,  1, 116, 'Drum & Perc',        'Concert Bass Drum'])
sounds.append([121,  0, 117, 'Drum & Perc',        'Melodic Tom'])
sounds.append([121,  1, 117, 'Drum & Perc',        'Melodic Tom 2'])
sounds.append([121,  2, 117, 'Drum & Perc',        'Reverse Tom'])
sounds.append([121,  0, 118, 'Drum & Perc',        'Synth Drum'])
sounds.append([121,  1, 118, 'Drum & Perc',        'Rhythm Box Tom'])
sounds.append([121,  2, 118, 'Drum & Perc',        'Electronic Drum'])
sounds.append([121,  3, 118, 'Drum & Perc',        'Reverse Snare'])
sounds.append([121,  0, 119, 'Drum & Perc',        'Reverse Cymbal'])
sounds.append([121,  1, 119, 'Drum & Perc',        'Dragon Gong'])
sounds.append([121,  0, 120, 'SFX',                'Guitar Fret Noise'])
sounds.append([121,  1, 120, 'SFX',                'Guitar Cut Noise'])
sounds.append([121,  2, 120, 'SFX',                'Acoustic Bass String'])
sounds.append([121,  3, 120, 'Guitar',             'Vox Wah Chick'])
sounds.append([121,  0, 121, 'SFX',                'Breath Noise'])
sounds.append([121,  1, 121, 'Woodwind',           'Flute Click'])
sounds.append([121,  0, 122, 'SFX',                'Seashore'])
sounds.append([121,  1, 122, 'SFX',                'Rain'])
sounds.append([121,  2, 122, 'SFX',                'Thunder'])
sounds.append([121,  3, 122, 'SFX',                'Wind'])
sounds.append([121,  4, 122, 'SFX',                'Stream'])
sounds.append([121,  5, 122, 'SFX',                'Bubble'])
sounds.append([121,  0, 123, 'SFX',                'Bird Tweet'])
sounds.append([121,  1, 123, 'SFX',                'Dog'])
sounds.append([121,  2, 123, 'SFX',                'Horse Gallop'])
sounds.append([121,  3, 123, 'SFX',                'Bird Tweet 2'])
sounds.append([121,  0, 124, 'SFX',                'Telephone 1'])
sounds.append([121,  1, 124, 'SFX',                'Telephone 2'])
sounds.append([121,  2, 124, 'SFX',                'Door Creak'])
sounds.append([121,  3, 124, 'SFX',                'Door'])
sounds.append([121,  4, 124, 'SFX',                'Scratch'])
sounds.append([121,  5, 124, 'SFX',                'Wind Chime'])
sounds.append([121,  0, 125, 'SFX',                'Helicopter'])
sounds.append([121,  1, 125, 'SFX',                'Car Engine'])
sounds.append([121,  2, 125, 'SFX',                'Car Stop'])
sounds.append([121,  3, 125, 'SFX',                'Car Pass'])
sounds.append([121,  4, 125, 'SFX',                'Car Crash'])
sounds.append([121,  5, 125, 'SFX',                'Siren'])
sounds.append([121,  6, 125, 'SFX',                'Train'])
sounds.append([121,  7, 125, 'SFX',                'Jetplane'])
sounds.append([121,  8, 125, 'SFX',                'Starship'])
sounds.append([121,  9, 125, 'SFX',                'Burst Noise'])
sounds.append([121,  0, 126, 'SFX',                'Applause'])
sounds.append([121,  1, 126, 'SFX',                'Laughing'])
sounds.append([121,  2, 126, 'SFX',                'Screaming'])
sounds.append([121,  3, 126, 'SFX',                'Punch'])
sounds.append([121,  4, 126, 'SFX',                'Heart Beat'])
sounds.append([121,  5, 126, 'SFX',                'Footsteps'])
sounds.append([121,  6, 126, 'SFX',                'Stadium'])
sounds.append([121,  0, 127, 'SFX',                'Gun Shot'])
sounds.append([121,  1, 127, 'SFX',                'Machine Gun'])
sounds.append([121,  2, 127, 'SFX',                'Laser Gun'])
sounds.append([121,  3, 127, 'SFX',                'Explosion'])
sounds.append([121, 64,   0, 'Special',            'Gospel Organ V'])
sounds.append([121, 64,   1, 'Special',            'Organ Low 1 V'])
sounds.append([121, 64,   2, 'Special',            'Organ Low 2 V'])
sounds.append([121, 64,   3, 'Special',            'Organ Hi V'])
sounds.append([121, 64,   4, 'Special',            'Trumpet Pro 1'])
sounds.append([121, 64,   5, 'Special',            'Trumpet Pro 2'])
sounds.append([121, 64,   6, 'Special',            'Tight Brass 3'])
sounds.append([121, 64,   7, 'Special',            'Power Brass'])
sounds.append([121, 64,   8, 'Special',            'Brass & Sax'])
sounds.append([121, 64,   9, 'Special',            'Clean Guitar V'])
sounds.append([121, 64,  10, 'Special',            'Finger Bass 2'])
sounds.append([121, 64,  11, 'Special',            'Finger Bass 3'])
sounds.append([121, 64,  12, 'Special',            'Finger Bass 4'])
sounds.append([121, 64,  13, 'Special',            'M1 Organ 2'])
sounds.append([121, 64,  14, 'Special',            'Kick Bass 1'])
sounds.append([121, 64,  15, 'Special',            'Kick Bass 2'])
sounds.append([121, 64,  16, 'Special',            'Knocking Bass 1'])
sounds.append([121, 64,  17, 'Special',            'Knocking Bass 2'])
sounds.append([121, 64,  18, 'Special',            'Octave Bass'])
sounds.append([121, 64,  19, 'Special',            'Detuned Pad 1'])
sounds.append([121, 64,  20, 'Special',            'Detuned Pad 2'])
sounds.append([121, 64,  21, 'Special',            'Dark Pad'])
sounds.append([121, 64,  22, 'Special',            'Saw Pad'])
sounds.append([121, 64,  23, 'Special',            'Old Poly 1'])
sounds.append([121, 64,  24, 'Special',            'Old Poly 2'])
sounds.append([121, 64,  25, 'Special',            'Old Poly 3'])
sounds.append([121, 64,  26, 'Special',            'Saw Pizzicato'])
sounds.append([121, 64,  27, 'Special',            'Pulse Pizzicato'])
sounds.append([121, 64,  28, 'Special',            'Square Pizzicato'])
sounds.append([121, 64,  29, 'Special',            'FM Pizzicato'])
sounds.append([121, 64,  30, 'Special',            'Wire Pizzicato'])
sounds.append([121, 64,  31, 'Special',            'D-Saw Pizzicato'])
sounds.append([121, 64,  32, 'Special',            'Digi Pizzicato'])
sounds.append([121, 64,  33, 'Special',            'Mallet Pizzicato'])
sounds.append([121, 64,  34, 'Special',            'EDM Voice'])
sounds.append([121, 64,  35, 'Special',            'Voice Lead'])
sounds.append([121, 64,  36, 'Special',            'Bottle Lead'])
sounds.append([121, 64,  37, 'Special',            'Lo-Fi Square'])
sounds.append([121, 64,  38, 'Special',            'Pizzicato Hit'])
sounds.append([121, 64,  39, 'Special',            'Brass & String Hit'])
sounds.append([121, 65,   0, 'Special',            'Breeze Lead'])
